### ISSUE TITLE
Add more non-throwing helper functions

### ISSUE THREAD

**Issue by bigwad** [dcleblanc/SafeInt#7]
There exists a limited set of helpers that covers a subset of SafeInt's overloaded operators. I'm unsure how this subset was chosen, but I guess in the end all overloaded operators should have a counterpart non-throwing helper.
So far I'm missing SafeNegate the most.

**Comment by dcleblanc** [comment]
The operators were chosen based on what we needed during the initial use of the library in Office, and I also would try to be consistent - so when SafeGreaterThan came in, so did <, <= and >=. It does seem handy to have negation as a specific check, so I created it. It's currently in a branch because I haven't verified all the other compilers yet. Should be OK, but need to test gcc and clang. Also added test coverage.

Please take a look, see if this is what you expected.

**Comment by dcleblanc** [comment]
Done
