### ISSUE TITLE
no support for HW overflow checks

### ISSUE THREAD

**Issue by manbearian** [dcleblanc/SafeInt#9]
I was looking over the code generated for some of the safe-int checks and I noticed that HW overflow checking isn't used on platforms that support it. For example using Intel's jump-on-overflow instruction.

I've included a [Compiler Explorer example](https://godbolt.org/z/Cx6B5C) that demonstrates the code produced by the exsiting SafeInt code and a possible alternative that leverages HW overflow checking.

**Comment by dcleblanc** [comment]
There's a couple of reasons for this. The first is that as soon as you start putting assembly in your code, the compiler thinks you are smarter than it is, and doesn't optimize. My friend Michael Howard tried this some time ago, and it didn't go well. The second reason is that there's a lot of overflows that don't trip the overflow flag. For example, a casting truncation won't set it, and it also has false positives:

int main(int, char**)
{
    long int a;
    long int b = 0x7fffffff;
    int c = 2;

    a = b + c;

    return 0;
}

This will set the flag, but shouldn't.

What gets you the most gain is using intrinsics, but those currently only work on the Visual Studio compiler. If you know how to find analogous intrinsics I can support on clang and gcc, I'd be happy to work on including those.

**Comment by manbearian** [comment]
Agree you cannot always use the HW support, but seems like in some cases it should be possible. 
FYI, GCC provides built-ins for overflow checking: https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html

Is this something you've already tried?

it defintely seems possible that the explict range checks `if (x < y) throw()` are more likely to be optimzied away than the overflow check, but getting the compiler's optimzer to support this should be straightforward if its not already done.

**Comment by mwinterb** [comment]
(FYI, Clang supports the same builtins. They're supported in constexpr, at least for of them, as of 7.1 and 7.0, based on what CE has active.)
The distinction is easier to see here: https://godbolt.org/z/36NfHD, since it's more obvious that @manbearian made no mods to SafeInt code directly.

**Comment by dcleblanc** [comment]
I have tried inline assembler, and it didn't go well. Like I said, you lose your optimizations, and that hurts you more than it gains you. The other is that to really know if it would help, then you'd have to run through _all_ the test cases in the test harness (could start with just multiply), see if it is actually an overflow, and then see if the flag is set. Then once you know whether it actually works for that combination of types, you'd have to see if the template specialization that deals with that case doesn't have a mix of correct and incorrect behaviors. Finally, you'd have to see if something like this:

unsigned int32 x = 0x80000000;
unsigned int32 y = 2;
unsigned int64 test = (unsigned int64)x * (unsigned int64)y;

 return (test & 0xffffffff00000000) ? fail : succeed;

Doesn't actually work as well or better. And then you'd want to find out what happens when the parameters are compile time constants, and whether it optimizes away correctly.

So, if you'd like to poke at that, I'd be interested in learning the results. I haven't looked into it recently.

**Comment by dcleblanc** [comment]
Using the built-ins, at least for multiplication, looks like a win, and I already have an #ifdef around whether we have intrinsics support, it wouldn't be hard to sort out which compiler and use the correct intrinsics.

I don't currently have a minimum version of the compiler for either clang or gcc, so I would need to be able to test whether these are supported - it looks like a fairly recent addition. Would you @mwinterb happen to know how I might do that?

I'd like to add support for this, because it made a huge difference in the Windows code for 64-bit multiplication in terms of code size.

**Comment by mwinterb** [comment]
GCC added support in 5.1, released in April 2015. Clang introduced support for them in 3.4, in 2014.
With clang, it's fairly easy to test if they're supported, there's a __has_builtin function macro, e.g.
```
#if __has_builtin(__builtin_add_overflow)
    if (__builtin_add_overflow(x, y, &result))
        fail();
    return result;
#else
    // do it the normal way
#endif
```
For GCC, it requires inspection of the GCC version:
```
#if (__GNUC__ > 5) || ((__GNUC__ == 5) && (__GNUC_MINOR__ > 1))
```

**Comment by dcleblanc** [comment]
Cool, that's really helpful. I will add those where I currently have intrinsic support now. Maybe have it available in a branch in a couple of weeks.

**Comment by dcleblanc** [comment]
I apologize for the very long delay, but I believe this is fixed. See the fix/intrinsic branch.

**Comment by dcleblanc** [comment]
Fixed

**Comment by tiagomacarios** [comment]
Where can I find the fix/intrinsic branch?

MSVC just added support for intrinsics and I am wondering how much work would it be to use it.
https://developercommunity.visualstudio.com/t/Please-implement-integer-overflow-detect/409051#T-ND10436626

**Comment by dcleblanc** [comment]
It's been in the master branch for over 2 years. It detects compiler, and then will use the intrinsics appropriate to that compiler, unless you set a #define to tell it not to use intrinsics.

**Comment by dcleblanc** [comment]
It looks to me like you're asking for intrinsic support for a wider range of operations. That would be a whole new feature. Using intrinsics for 64-bit multiplication was a significant win, I'd have to spend some time checking to see whether some of these others are actually a perf improvement - they might not be.

For example, the article you referenced mentioned an int32 add check. The existing code to check that is highly efficient, and I don't think using the intrinsic would be a win. There could be some types where it would help, it would have to be considered on a case by case basis.
